services:
  - type: web
    name: blog-web
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn Blogger.wsgi:application --bind 0.0.0.0:8000
    preDeployCommand: |
      python manage.py collectstatic --noinput
      python manage.py migrations
      python manage.py migrate  