# Generated by Django 4.2.20 on 2025-05-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0003_comment_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="featured_image",
            field=models.ImageField(blank=True, null=True, upload_to="blog_images"),
        ),
    ]
