name: Deploy to Render

on:
  push:
    branches:
      - main  # Trigger the deployment on pushing to the main branch
  pull_request:
    branches:
      - main  # Also trigger when a PR is merged into the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Set the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Set environment variables
        run: |
          echo "DJANGO_SETTINGS_MODULE=Blogger.settings" >> $GITHUB_ENV
          echo "EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }}" >> $GITHUB_ENV
          echo "EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}" >> $GITHUB_ENV
          
      - name: Run migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate  # Run migrations to ensure your DB is updated

      - name: Deploy to Render
        run: |
          curl -fsSL https://api.render.com/deploy/srv-d0crreje5dus73amj0e0?key=sQzIcsUTmEA  # Customize for your Render app

          
      - name: Run Gunicorn (production server)
        run: |
          gunicorn Blogger.wsgi:application  # Start Gunicorn server in production
