on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend-ci:
    runs-on: ubuntu-latest
    outputs:
      ci-success: ${{ steps.set-output.outputs.success }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate

      - name: Tests
        run: |
          # Run your tests here
          echo "Tests passed"

      - name: Set output
        id: set-output
        run: echo "success=true" >> $GITHUB_OUTPUT

  backend-deploy:
    needs: backend-ci
    if: needs.backend-ci.outputs.ci-success == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Backend Deploy
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_BACKEND_SERVICE_ID }}
          api-key:    ${{ secrets.RENDER_API_KEY }}
