name: Integrations

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set DJANGO_SETTINGS_MODULE
        run: |
          echo "DJANGO_SETTINGS_MODULE=Blogger.settings" >> $GITHUB_ENV

      - name: Run tests
        run: |
          pytest
