on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend-ci:
    runs-on: ubuntu-latest
    outputs:
      ci-success: ${{ steps.set-output.outputs.success }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set environment variables
        run: |
          echo "DJANGO_SETTINGS_MODULE=Blogger.settings" >> $GITHUB_ENV
          echo "EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }}" >> $GITHUB_ENV
          echo "SECRET_KEY=${{secrets.SECRET_KEY}}" >> $GITHUB_ENV
          echo "EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}" >> $GITHUB_ENV

      - name: Run migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate
      
      # - name: Load initial data
      #   run: |
      #     python manage.py --ignore=contenttypes loaddata initial_data.json

      - name: Tests
        run: |
          # Run your tests here
          echo "Tests passed"

      - name: Set output
        id: set-output
        run: echo "success=true" >> $GITHUB_OUTPUT

  backend-deploy:
    needs: backend-ci
    if: needs.backend-ci.outputs.ci-success == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Backend Deploy
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_BACKEND_SERVICE_ID }}
          api-key:    ${{ secrets.RENDER_API_KEY }}
