services:
  - type: web
    name: blog-001k
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:8000 Blogger.wsgi:application
    preDeployCommand: |
      python manage.py makemigrations
      python manage.py migrate
